### ISSUE TITLE
LocalPCInfo/SystemVolume & SpeakerLevel not working in V96

### ISSUE THREAD

**Issue by puterjam** [Aurora-RGB/Aurora#108]
The latest version, System Audio in LocalPCInfo, is not very stable.
I use QMK keyboard, through OpenRGB protocol.

Aurora Version:
v96

**Comment by Aytackydln** [comment]
Can you provide more info? What is the current behaviour? If there are errors, also post the logs

**Comment by puterjam** [comment]
in V95, Sometimes there are exceptions [error]。Switch sound devices，may working again.

```
[ERROR] 22:55:21: Error updating overlay layers: System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'NAudio.CoreAudioApi.Interfaces.IMMDevice'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{D666063F-1587-4E43-81F1-B948E807363F}' failed due to the following error: 不支持此接口 (0x80004002 (E_NOINTERFACE)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at NAudio.CoreAudioApi.Interfaces.IMMDevice.Activate(Guid& id, ClsCtx clsCtx, IntPtr activationParams, Object& interfacePointer)
   at NAudio.CoreAudioApi.MMDevice.GetAudioEndpointVolume()
   at Aurora.Profiles.LocalPcInformation.get_SystemVolumeIsMuted() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\LocalPCInformation.cs:line 58
   at Aurora.Profiles.LocalPcInformation.get_SystemVolume() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\LocalPCInformation.cs:line 53
   at FastMember_dynamic.LocalPcInformation_2.get_Item(Object , String )
   at Aurora.Utils.FastMemberExtensions.ResolvePropertyPath(Object target, String path) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Utils\FastMemberExtensions.cs:line 19
   at Aurora.Profiles.GameState.GetNumber(String path) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\GameState.cs:line 94
   at Aurora.Settings.Layers.PercentGradientLayerHandler.Render(IGameState state) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Settings\Layers\PercentGradientLayerHandler.cs:line 52
   at Aurora.Settings.Layers.Layer.Render(IGameState gs) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Settings\Layers\Layer.cs:line 61
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.Queue`1..ctor(IEnumerable`1 collection)
   at Aurora.Profiles.LightEvent.UpdateOverlayLights(EffectFrame frame) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\LightEvent.cs:line 81 
```

but, in V96. no any error  in log 

LocalPCInfo/SystemVolume & LocalPCInfo/SpeakerLevel maybe unable to get value?

**Comment by Aytackydln** [comment]
![image](https://user-images.githubusercontent.com/11393706/207091564-03aa45d8-9def-42ff-b94f-f32096af8d84.png)
can you check your selected devices in aurora settings? Sound devices in LocalPCInfo are determined from there

**Comment by tcutchi** [comment]
I have the same issue, attaching two videos to show V94 vs V96 volume behavior.

V94:
https://user-images.githubusercontent.com/5715576/208120321-1da05a07-d483-4d36-9035-ab4ecda727b2.mp4
(Skipping V95 as it did not work for me at all)
V96:
https://user-images.githubusercontent.com/5715576/208120353-d1154d66-c2be-4224-9a80-2b26fc8f393b.mp4

V96 logs:
[2022-12-16 08.33.14.log](https://github.com/Aurora-RGB/Aurora/files/10246586/2022-12-16.08.33.14.log)

**Comment by Aytackydln** [comment]
can you try with latest release?
https://github.com/Aurora-RGB/Aurora/releases/tag/v98

**Comment by Aytackydln** [comment]
it seems value range changed from 0-100 value to 0-1 range. For workaround you can set max value to 0 for now

**Comment by puterjam** [comment]
Cool. I try the lastest release v98. and set max value  to 1.  Everything is fine now.
