### ISSUE TITLE
LoadLibrary failed with error code 0

### ISSUE THREAD

**Issue by MattJF90** [Aurora-RGB/Aurora#169]
### Expected Behaviour
Corsair (RGB.NET) and Logitech (RGB.NET) should start successfully and control the keyboard and mouse respectively.

### Actual Behaviour
Both the Corsair (RGB.NET) and Logitech (RGB.NET) devices fail to load with message "Corsair/Logitech LoadLibrary failed with error code 0".

### Reproduction steps
1. Start Aurora, with Corsair (RGB.NET) and Logitech (RGB.NET) enabled in Device Manager.

### Frequency
The majority of times.
Once in awhile, it will work correctly after a system restart, but this is probably only 10% of the time.

### Aurora Version:
v171

### Previously an Issue?
Yes
- v169

### System Information
**Device Manager:**
- Corsair (RGB.NET) enabled
- Logitech (RGB.NET) enabled
- All other devices disabled

**Wrappers:**
- Chroma 3.29.1 (Connection: Success)

**Keyboard/Mouse software installed:**
- Corsair iCue 5.4.98
- Logitech Gaming Software 9.02.74

**Devices:**
- Keyboard: Corsair K70 RGB PRO
- Mouse: Logitech G502

### Stack Trace
`2023-08-13 12:19:10.192 [ERR] Device provider Corsair (RGB.NET) threw exception
RGB.NET.Core.RGBDeviceException: Corsair LoadLibrary failed with error code 0
   at RGB.NET.Devices.CorsairLegacy.Native._CUESDK.LoadCUESDK()
   at RGB.NET.Devices.CorsairLegacy.Native._CUESDK.Reload()
   at RGB.NET.Devices.CorsairLegacy.CorsairLegacyDeviceProvider.InitializeSDK()
   at RGB.NET.Core.AbstractRGBDeviceProvider.Initialize(RGBDeviceType loadFilter, Boolean throwExceptions)`

`2023-08-13 12:19:10.295 [ERR] Device provider Logitech (RGB.NET) threw exception
RGB.NET.Core.RGBDeviceException: Logitech LoadLibrary failed with error code 0
   at RGB.NET.Devices.Logitech.Native._LogitechGSDK.LoadLogitechGSDK()
   at RGB.NET.Devices.Logitech.Native._LogitechGSDK.Reload()
   at RGB.NET.Devices.Logitech.LogitechDeviceProvider.InitializeSDK()
   at RGB.NET.Core.AbstractRGBDeviceProvider.Initialize(RGBDeviceType loadFilter, Boolean throwExceptions)`

**Comment by MattJF90** [comment]
Note: If I switch from Logitech (RGB.NET) to Logitech, I'm able to get lighting effects on my Logitech mouse again. This issue seems to just affect the RGB.NET instances in device manager.

Unfortunately, the native support for Corsair seems to have been removed at some point, so I am unable to switch back to that for my keyboard and am forced to use the RGB.NET variant.

**Comment by Aytackydln** [comment]
Sorry, this is the first time I'm seeing this issue. This is very likely related to your system

I will investigate more but I can't seem to think of anything yet.

Your keyboard is also not yet supported by OpenRGB, so old Corsair device would help you but I don't want to bring old codes back and delegating that functionality simplifies my work a lot.

I know Artemis only uses RGB.NET libraries but did you try it? If it works there it would mean it is related to Aurora's way of hanlding the library. If Artemis also doesn't work, Artemis's developers are way more experienced than me about these types of things.

**Comment by MattJF90** [comment]
Artemis appears to work correctly and is able to detect my devices no problem.

This issue seems to just be with Aurora on the most recent versions - it used to work fine on earlier versions with the native driver, and I think with the RGB.NET driver too. Not sure if something changed recently that broke it?

**Comment by Aytackydln** [comment]
don't know if you still use Aurora but does this still happen?
