### ISSUE TITLE
Layers fail to render

### ISSUE THREAD

**Issue by M-Creeper** [Aurora-RGB/Aurora#218]
### Expected Behaviour (if not obvious)
Aurora should be displaying certain visuals on my keyboard when playing CS2 like "Death Effect" and normal Background.

### Actual Behaviour
When ingame it tries to set up the background for the keyboard, it quickly lights up, then it goes back to black. Overlay keys are not affected and display as they should

### Reproduction steps
Simply playing the game, also in Aurora under preview sliding the health preview to zero (which would follow a death effect, triggers it.

### Aurora Version:
v268

### Previously an Issue?
No issues previously

Logs:

Aurora-2024-06-25 20:52:33.534 [INF] 
========================================
Operation System: Windows 10 Pro                                                      <----- Not true, I use 11 Pro
Environment OS Version: Microsoft Windows NT 10.0.22631.0
System Directory: C:\Windows\system32
Executing Directory: C:\Program Files\Aurora
Launch Directory: C:\Program Files\Aurora
Processor Count: 20
Environment Version: 8.0.5
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: v268
========================================
Aurora-2024-06-25 20:52:33.540 [INF] Loading Configuration
Aurora-2024-06-25 20:52:33.611 [INF] Loading Input Hooking
Aurora-2024-06-25 20:52:33.612 [INF] Loading Device Manager...
Aurora-2024-06-25 20:52:33.616 [INF] Loaded Input Hooking
Aurora-2024-06-25 20:52:33.621 [INF] Starting IpcListener
Aurora-2024-06-25 20:52:33.621 [INF] Fetching latest pointers
Aurora-2024-06-25 20:52:33.624 [INF] Loaded Device Manager
Aurora-2024-06-25 20:52:33.625 [INF] Initializing Lightsync...
Aurora-2024-06-25 20:52:33.626 [INF] Loading RazerSdkManager
Aurora-2024-06-25 20:52:33.626 [INF] [IPCServer] Pipe created {}
Aurora-2024-06-25 20:52:33.626 [INF] [AuroraCommandsServerIPC] Pipe created {}
Aurora-2024-06-25 20:52:33.626 [INF] Listening for wrapper integration calls...
Aurora-2024-06-25 20:52:33.627 [INF] Loading Plugins
Aurora-2024-06-25 20:52:33.627 [INF] Loading Applications
Aurora-2024-06-25 20:52:33.632 [INF] Loading KB Layouts
Aurora-2024-06-25 20:52:33.634 [INF] Loaded Plugins
Aurora-2024-06-25 20:52:33.736 [INF] NVAPI
Aurora-2024-06-25 20:52:33.736 [INF] Version: NVidia Complete Version 1.10
Aurora-2024-06-25 20:52:33.739 [INF] Number of GPUs: 1
Aurora-2024-06-25 20:52:33.843 [INF] Loaded Applications
Aurora-2024-06-25 20:52:33.897 [INF] [AuroraCommandsServerIPC] Pipe connection established
Aurora-2024-06-25 20:52:33.898 [INF] Received command: remappableDevices~{"Devices":[]}
Aurora-2024-06-25 20:52:34.166 [INF] Loading ConfigUI...
Aurora-2024-06-25 20:52:34.167 [INF] LGS Pipe name: LGS_LED_SDK-00000001
Aurora-2024-06-25 20:52:34.167 [INF] Initialized Lightsync
Aurora-2024-06-25 20:52:34.169 [ERR] Registry not available, Query: SELECT * FROM RegistryValueChangeEvent WHERE Hive='HKEY_LOCAL_MACHINE' AND KeyPath='SOFTWARE\\\\WOW6432Node\\\\Razer Chroma SDK\\\\Apps' AND ValueName='PriorityList'
Aurora-2024-06-25 20:52:34.172 [FTL] RazerSdkManager failed to load!
System.InvalidOperationException: RzSdkService is not running.
   at RazerSdkReader.ChromaReader.Start()
   at AuroraRgb.Modules.Razer.ChromaSdkManager.TryLoadChroma() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Modules\Razer\ChromaSdkManager.cs:line 86
   at AuroraRgb.Modules.Razer.ChromaSdkManager.Initialize() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Modules\Razer\ChromaSdkManager.cs:line 32
Aurora-2024-06-25 20:52:34.179 [WRN] Currently installed razer sdk version "0.0.0" is not supported by the RazerSdkManager!
Aurora-2024-06-25 20:52:34.335 [INF] Waiting for modules...
Aurora-2024-06-25 20:52:34.340 [INF] Loaded KB Layouts
Aurora-2024-06-25 20:52:34.588 [INF] Updating Online Settings
Aurora-2024-06-25 20:52:36.098 [INF] Modules initiated
Aurora-2024-06-25 20:52:38.307 [WRN] Closed process deploymentagent.exe didn't exist in the list
Aurora-2024-06-25 20:52:41.065 [ERR] Layer render error
System.NullReferenceException: Object reference not set to an instance of an object.
   at AuroraRgb.Profiles.CSGO.Layers.CSGOBackgroundLayerHandler.Render(IGameState state) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\CSGO\Layers\CSGOBackgroundLayerHandler.cs:line 83
   at AuroraRgb.Settings.Layers.Layer.Render(IGameState gs) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Settings\Layers\Layer.cs:line 66
Aurora-2024-06-25 20:56:32.471 [ERR] Layer render error
System.NullReferenceException: Object reference not set to an instance of an object.
   at AuroraRgb.Profiles.CSGO.Layers.CSGOBackgroundLayerHandler.Render(IGameState state) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\CSGO\Layers\CSGOBackgroundLayerHandler.cs:line 83
   at AuroraRgb.Settings.Layers.Layer.Render(IGameState gs) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Settings\Layers\Layer.cs:line 66
Aurora-2024-06-25 20:57:59.421 [ERR] Layer render error
System.NullReferenceException: Object reference not set to an instance of an object.
   at AuroraRgb.Profiles.CSGO.Layers.CSGOBackgroundLayerHandler.Render(IGameState state) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\CSGO\Layers\CSGOBackgroundLayerHandler.cs:line 83
   at AuroraRgb.Settings.Layers.Layer.Render(IGameState gs) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Settings\Layers\Layer.cs:line 66
Aurora-2024-06-25 20:58:43.000 [ERR] Layer render error
System.NullReferenceException: Object reference not set to an instance of an object.
   at AuroraRgb.Profiles.CSGO.Layers.CSGOBackgroundLayerHandler.Render(IGameState state) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\CSGO\Layers\CSGOBackgroundLayerHandler.cs:line 83
   at AuroraRgb.Settings.Layers.Layer.Render(IGameState gs) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Settings\Layers\Layer.cs:line 66
Aurora-2024-06-25 20:59:13.024 [ERR] Layer render error
System.NullReferenceException: Object reference not set to an instance of an object.
   at AuroraRgb.Profiles.CSGO.Layers.CSGOBackgroundLayerHandler.Render(IGameState state) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\CSGO\Layers\CSGOBackgroundLayerHandler.cs:line 83
   at AuroraRgb.Settings.Layers.Layer.Render(IGameState gs) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Settings\Layers\Layer.cs:line 66
Aurora-2024-06-25 21:00:44.403 [ERR] Layer render error
System.NullReferenceException: Object reference not set to an instance of an object.
   at AuroraRgb.Profiles.CSGO.Layers.CSGOBackgroundLayerHandler.Render(IGameState state) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\CSGO\Layers\CSGOBackgroundLayerHandler.cs:line 83
   at AuroraRgb.Settings.Layers.Layer.Render(IGameState gs) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Settings\Layers\Layer.cs:line 66

**Comment by Aytackydln** [comment]
Thanks, issues are mostly fixed with last update
