### ISSUE TITLE
Crash when clicking on Overlay Layers on CS2 default profile

### ISSUE THREAD

**Issue by cchrkk** [Aurora-RGB/Aurora#236]
### Reproduction steps

Fresh Install (deleted all aurora folders in appdata), enabled CS2 overlay + profile, clicked on Overlay Layers, this error comes up every time and crashes aurora, it's weird because the default profile has no layers

```
Aurora-2024-09-24 22:32:49.175 [ERR] Error updating overlay layers
System.NullReferenceException: Object reference not set to an instance of an object.
   at AuroraRgb.Profiles.LightEvent.UpdateOverlayLights(EffectFrame frame) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\LightEvent.cs:line 69
Aurora-2024-09-24 22:32:52.243 [FTL] Fatal Exception caught
System.NullReferenceException: Object reference not set to an instance of an object.
   at AuroraRgb.Settings.Controls.Control_ProfileManager.btnProfileReset_Click(Object sender, RoutedEventArgs e) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Settings\Controls\Control_ProfileManager.xaml.cs:line 152
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
### Aurora Version:

v291
### Previously an Issue?

Don't know

[2024-09-24 20.32.22.log](https://github.com/user-attachments/files/17121357/2024-09-24.20.32.22.log)

**Comment by Aytackydln** [comment]
Thanks for reporting. Released new version, check it out

**Comment by cchrkk** [comment]
> Thanks for reporting. Released new version, check it out

Resetting profile manually worked, but I have this issues in Preview tab:
- Health and armor indicators are not working
![image](https://github.com/user-attachments/assets/2be96909-2fcb-4817-ab9c-c35d4e723255)
- Aurora crashes every time i press Mimic respawn button 
![image](https://github.com/user-attachments/assets/3f876476-7856-4ffc-8015-aefc07643441)
I pressed
