### ISSUE TITLE
Aurora/Aurora-Updater crashes when putting computer to sleep.

### ISSUE THREAD

**Issue by middleagedman** [Aurora-RGB/Aurora#73]
### Expected Behaviour
Not crashing

### Actual Behaviour
Putting Windows 11 Pro to sleep, resume from sleep and see that the aurora process died.  Multiple event logs show the following (pasted in order from earliest to latest)

Event 1026, .NET Runtime - 11:53:14 PM EST
Application: Aurora-Updater.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at Aurora.Settings.Configuration..ctor()
   at Aurora_Updater.UpdateManager.LoadSettings()
   at Aurora_Updater.UpdateManager..ctor(SemVer.Version, System.String, System.String)
   at Aurora_Updater.Program.Main(System.String[])

Event 1000, Application Error - 11:53:14 PM EST
Faulting application name: Aurora-Updater.exe, version: 1.0.0.0, time stamp: 0x9462715c
Faulting module name: KERNELBASE.dll, version: 10.0.22000.918, time stamp: 0xb42fa627
Exception code: 0xe0434352
Fault offset: 0x000000000004474c
Faulting process id: 0x64b0
Faulting application start time: 0x01d8c011dbdc8946
Faulting application path: C:\Program Files\Aurora\Aurora-Updater.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 0af233b3-757d-43b4-ae5c-23eeeb130467
Faulting package full name: 
Faulting package-relative application ID: 

Event 1026, .NET Runtime - 11:58:41 PM EST
Application: Aurora.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at LightFXAPI.LightFXSDK.LFX_Reset()
   at Aurora.Devices.LightFX.LightFxDevice.UpdateDevice(System.Collections.Generic.Dictionary`2<Aurora.Devices.DeviceKeys,System.Drawing.Color>, System.ComponentModel.DoWorkEventArgs, Boolean)
   at Aurora.Devices.LightFX.LightFxDevice.UpdateDevice(Aurora.Devices.DeviceColorComposition, System.ComponentModel.DoWorkEventArgs, Boolean)
   at Aurora.Devices.DeviceContainer.WorkerOnDoWork(System.ComponentModel.DoWorkEventArgs)
   at Amib.Threading.Internal.WorkItemsGroupBase+<>c__DisplayClass40_0.<QueueWorkItem>b__0(System.Object)
   at Amib.Threading.Internal.WorkItem.ExecuteWorkItem()
   at Amib.Threading.Internal.WorkItem.Execute()
   at Amib.Threading.SmartThreadPool.ExecuteWorkItem(Amib.Threading.Internal.WorkItem)
   at Amib.Threading.SmartThreadPool.ProcessQueuedItems()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

Event 1000, Application Error - 11:58:41 PM EST
Faulting application name: Aurora.exe, version: 0.0.0.0, time stamp: 0xb3b1d5f6
Faulting module name: LightFX.dll, version: 5.2.0.0, time stamp: 0x62e20cf5
Exception code: 0xc0000005
Fault offset: 0x0000000000001244
Faulting process id: 0x782c
Faulting application start time: 0x01d8c011db6302e4
Faulting application path: C:\Program Files\Aurora\Aurora.exe
Faulting module path: C:\WINDOWS\SYSTEM32\LightFX.dll
Report Id: 884868e6-d2ec-4ddc-802f-0196a3cef61f
Faulting package full name: 
Faulting package-relative application ID: 

### Reproduction steps
Put Windows 11 Pro to sleep

### Frequency
Every time

### Aurora Version:
v65 Aurora-RGB/Aurora

### Previously an Issue?
Don't know

Logs attached from event time:

[2022-09-03 23.53.13.log](https://github.com/Aurora-RGB/Aurora/files/9485229/2022-09-03.23.53.13.log)

**Comment by Aytackydln** [comment]
Seems like a problem with LightFX controller in Aurora. Probably needs disabling/restarting with account lock. If you're not using LightFX devices you should disable it

**Comment by middleagedman** [comment]
You are 100% correct.. Disabling LightFX controller (and all other things not Razer) made it not crash anymore
