### ISSUE TITLE
aurora still running unless end in task manager

### ISSUE THREAD

**Issue by mechcentric** [Aurora-RGB/Aurora#97]
task tray quit does not work; context menu stuck on screen until end in task manager. this is part of how i get logitech sdk to start working after sleep.

**Comment by Aytackydln** [comment]
related to #55 
Can you try with v77? I've added new library to control Logitech devices

**Comment by mechcentric** [comment]
logitech mouse momentarily lights properly after sleep, then stops. It takes a while, but aurora is now able to quit from the tray, and the context menu stops hanging after a minute. close, but not quite. i appreciate your efforts.

**Comment by mechcentric** [comment]
It does give me a crash error message when I exit it... but it's not in task manager afterward anymore...

**Comment by Aytackydln** [comment]
Can you give me the error message or logs? Is cooler master device enabled?

**Comment by mechcentric** [comment]
Cooler Master device is not enabled.
![image](https://user-images.githubusercontent.com/45723202/199853827-bc4e112b-c173-4ea1-88fb-c7acb92c709c.png)

**Comment by kjstew** [comment]
I was also having this issue because of my Logitech keyboard. Disabling the persistent profile feature in GHUB fixed it for me (see https://github.com/Aurora-RGB/Aurora/issues/55#issuecomment-1214266955).

This did not fix the SDK failing to start after sleep however.

**Comment by Aytackydln** [comment]
@kjstew did you try RGB.NET controller from the latest version?

**Comment by kjstew** [comment]
The RGB.NET controller does not start for me. Here's the error thrown in logs:

```
[ERROR] 10:45:32: Device provider "LogitechDeviceProvider" threw critical exception RGB.NET.Core.RGBDeviceException: Can't find the Logitech-SDK at one of the expected locations:
 'C:\Program Files\Aurora\x64\LogitechLedEnginesWrapper.dll'
   at RGB.NET.Devices.Logitech.Native._LogitechGSDK.LoadLogitechGSDK()
   at RGB.NET.Devices.Logitech.Native._LogitechGSDK.Reload()
   at RGB.NET.Devices.Logitech.LogitechDeviceProvider.InitializeSDK()
   at RGB.NET.Core.AbstractRGBDeviceProvider.Initialize(RGBDeviceType loadFilter, Boolean throwExceptions)
```

**Comment by Aytackydln** [comment]
@kjstew can you do a clean installation and try rgb.net again?

**Comment by Aytackydln** [comment]
@kjstew sorry for late reply but can you try (rgb.net) again with clean installation? If it doesn't work again I will add the dll to aurora itself.

**Comment by kjstew** [comment]
@Aytackydln Sure, I will try when I can. I'm currently away from my desktop and will return in a week. Apologies for the delay
